name: Sync to Gitee

on:
  push:
    branches:
      - main

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Mirror the GitHub repo to Gitee
        uses: Yikun/hub-mirror-action@master
        with:
          src: github/your-github-username
          dst: gitee/your-gitee-username
          dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
          dst_token: ${{ secrets.GITEE_TOKEN }}
          static_list: "zyma"
          force_update: true
          debug: true
